// export const FETCH_ARTICLE_DATA_LIST = 'FETCH_ARTICLE_DATA_LIST';
// export const FETCHING_ARTICLE_DATA_LIST = 'FETCHING_ARTICLE_DATA_LIST';
export const SET_LOADING_ON = 'SET_LOADING_ON';
export const SET_LOADING_OFF = 'SET_LOADING_OFF';
export const FETCH_RECOMMEND_DATA = 'FETCH_RECOMMEND_DATA';
export const FETCHING_RECOMMEND_DATA = 'FETCHING_RECOMMEND_DATA';
// export const FETCHING_ARTICLE_DETAIL_DATA = 'FETCHING_ARTICLE_DETAIL_DATA';
// export const FETCH_ARTICLE_DETAIL_DATA = 'FETCH_ARTICLE_DETAIL_DATA';
export const FETCHING_CATEGORY_DATA = 'FETCHING_CATEGORY_DATA';
export const GET_CATEGORY_DATA_SUCCESS = 'GET_CATEGORY_DATA_SUCCESS';
// export const FETCHING_ARTICLE_DATA_PAGINATE = 'FETCHING_ARTICLE_DATA_PAGINATE';
// export const GET_ARTICLE_DATA_PAGINATE = 'GET_ARTICLE_DATA_PAGINATE';

export const FETCHING_GET_CONFIG_YOUTUBE = 'FETCHING_GET_CONFIG_YOUTUBE';
export const GETTING_GET_CONFIG_YOUTUBE = 'GETTING_GET_CONFIG_YOUTUBE';

export const FETCHING_USER_REVIEW = 'FETCHING_USER_REVIEW';
export const GETTING_USER_REVIEW = 'GETTING_USER_REVIEW';

export const FETCHING_YOUTUBE_REVIEW = 'FETCHING_YOUTUBE_REVIEW';
export const GETTING_YOUTUBE_REVIEW = 'GETTING_YOUTUBE_REVIEW';
