export default {
  PADDING: '50px',
  PADDING_XS: '15px',
  PADDING_SM: '20px',
  PADDING_MD: '30px',
  PADDING_LG: '60px',
  PADDING_XL: '80px',
  PADDING_XXL: '100px',

  IMAGE_COVER_LOGO: '300px',
  IMAGE_COVER_LOGO_XS: '500px',
  IMAGE_COVER_LOGO_SM: '500px',
  IMAGE_COVER_LOGO_MD: '300px',
  IMAGE_COVER_LOGO_LG: '300px',
  IMAGE_COVER_LOGO_XL: '300px',
  IMAGE_COVER_LOGO_XXL: '300px',
};
