export default {
  MIN_HEIGHT_SM: '24px',
  MIN_HEIGHT_MD: '26px',
  MIN_HEIGHT_LG: '31px',
  MIN_HEIGHT_XL: '35px',
  MIN_HEIGHT: '30px',

  MARGIN_LEFT: '50px',
  MARGIN_LEFT_SM: '20px',
  MARGIN_LEFT_MD: '25px',
  MARGIN_LEFT_LG: '50px',
  MARGIN_LEFT_XL: '50px',

  MARGIN_RIGHT: '50px',
  MARGIN_RIGHT_SM: '50px',
  MARGIN_RIGHT_MD: '50px',
  MARGIN_RIGHT_LG: '50px',
  MARGIN_RIGHT_XL: '50px',

  LOGO_HEIGHT: '87px',
  LOGO_HEIGHT_XS: '70px',
  LOGO_HEIGHT_SM: '70px',
  LOGO_HEIGHT_MD: '60px',
  LOGO_HEIGHT_LG: '60px',
  LOGO_HEIGHT_XL: '60px',

  LOGO_WIDTH: '250px',
  LOGO_WIDTH_XS: '120px',
  LOGO_WIDTH_SM: '80px',
  LOGO_WIDTH_MD: '200px',
  LOGO_WIDTH_LG: '60px',
  LOGO_WIDTH_XL: '60px',
};
